table dim_sede
	lineageTag: 07cebcbc-29cc-436e-b8ff-cfccf7bd918b

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 880e149d-c8f8-4812-a107-b2d7d9ac8519
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: d5ea2d40-7266-4441-b5b5-4c644c4f0e43
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 05ada7aa-6baa-4781-9992-809ce0173e26
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	partition dim_sede = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\alexi\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_sede_Table = Source{[Item="dim_sede",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_sede_Table,{{"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

