table Dim_Calendario
	lineageTag: 2c4350ec-05fb-44ae-8414-d5b7041d3d72

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: ee016bc9-22ef-446f-bae3-74b9181002b1
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: 85e6e3ae-4571-444c-9968-425d2cf54c9e
			defaultHierarchy: LocalDateTable_18afa1c5-c9fe-4cf0-8a4f-a8f0a52a6278.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 5852c8fe-3e18-4a91-821c-7d33e599dacb
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 054de775-7c0c-4c01-b7f7-5a9189afaebf
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 5c7d99c2-fd2c-45e5-b88b-a69b032dde85
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 7fc4a592-321c-4c8b-9fbe-22c161e7785e
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 95222018-9a88-4ec9-9a1a-9abbb8d7a415
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\alexi\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Source{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

